[tox]
envlist = py3.11,py3.12,py3.13,py.3.14
skip_missing_interpreters = True

[testenv]
deps = -r{toxinidir}/test-requirements.txt
commands = pytest -v

[testenv:flake8]
commands = flake8

[flake8]
ignore = E501
show-source = True
exclude = .venv,.tox,build,dist,doc,*egg
